[package]
distribution = "2201.2.1"
org= "ballerinax"
name= "microsoft.outlook.calendar"
version= "2.3.0"
authors = ["Ballerina"]
keywords = ["Productivity/Calendars", "Cost/Free", "Vendor/Microsoft"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.outlook.calendar"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
