[package]
org= "ballerinax"
name= "microsoft.outlook.calendar"
version= "1.0.1-SNAPSHOT"
authors = ["Ballerina"]
keywords = ["productivity/calendars", "cost/free", "vendor/microsoft"]
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.outlook.calendar"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
